export const cards = [
  "2_of_clubs.png",
  "3_of_clubs.png",
  "4_of_clubs.png",
  "5_of_clubs.png",
  "6_of_clubs.png",
  "7_of_clubs.png",
  "8_of_clubs.png",
  "9_of_clubs.png",
  "10_of_clubs.png",
  "jack_of_clubs.png",
  "queen_of_clubs.png",
  "king_of_clubs.png",
  "ace_of_clubs.png",

  "2_of_diamonds.png",
  "3_of_diamonds.png",
  "4_of_diamonds.png",
  "5_of_diamonds.png",
  "6_of_diamonds.png",
  "7_of_diamonds.png",
  "8_of_diamonds.png",
  "9_of_diamonds.png",
  "10_of_diamonds.png",
  "jack_of_diamonds.png",
  "queen_of_diamonds.png",
  "king_of_diamonds.png",
  "ace_of_diamonds.png",

  "2_of_hearts.png",
  "3_of_hearts.png",
  "4_of_hearts.png",
  "5_of_hearts.png",
  "6_of_hearts.png",
  "7_of_hearts.png",
  "8_of_hearts.png",
  "9_of_hearts.png",
  "10_of_hearts.png",
  "jack_of_hearts.png",
  "queen_of_hearts.png",
  "king_of_hearts.png",
  "ace_of_hearts.png",

  "2_of_spades.png",
  "3_of_spades.png",
  "4_of_spades.png",
  "5_of_spades.png",
  "6_of_spades.png",
  "7_of_spades.png",
  "8_of_spades.png",
  "9_of_spades.png",
  "10_of_spades.png",
  "jack_of_spades.png",
  "queen_of_spades.png",
  "king_of_spades.png",
  "ace_of_spades.png"
];

export const values = {
  // Clubs
  "2_of_clubs.png": 2,
  "3_of_clubs.png": 3,
  "4_of_clubs.png": 4,
  "5_of_clubs.png": 5,
  "6_of_clubs.png": 6,
  "7_of_clubs.png": 7,
  "8_of_clubs.png": 8,
  "9_of_clubs.png": 9,
  "10_of_clubs.png": 10,
  "jack_of_clubs.png": 10,
  "queen_of_clubs.png": 10,
  "king_of_clubs.png": 10,
  "ace_of_clubs.png": 11,

  // Diamonds
  "2_of_diamonds.png": 2,
  "3_of_diamonds.png": 3,
  "4_of_diamonds.png": 4,
  "5_of_diamonds.png": 5,
  "6_of_diamonds.png": 6,
  "7_of_diamonds.png": 7,
  "8_of_diamonds.png": 8,
  "9_of_diamonds.png": 9,
  "10_of_diamonds.png": 10,
  "jack_of_diamonds.png": 10,
  "queen_of_diamonds.png": 10,
  "king_of_diamonds.png": 10,
  "ace_of_diamonds.png": 11,

  // Hearts
  "2_of_hearts.png": 2,
  "3_of_hearts.png": 3,
  "4_of_hearts.png": 4,
  "5_of_hearts.png": 5,
  "6_of_hearts.png": 6,
  "7_of_hearts.png": 7,
  "8_of_hearts.png": 8,
  "9_of_hearts.png": 9,
  "10_of_hearts.png": 10,
  "jack_of_hearts.png": 10,
  "queen_of_hearts.png": 10,
  "king_of_hearts.png": 10,
  "ace_of_hearts.png": 11,

  // Spades
  "2_of_spades.png": 2,
  "3_of_spades.png": 3,
  "4_of_spades.png": 4,
  "5_of_spades.png": 5,
  "6_of_spades.png": 6,
  "7_of_spades.png": 7,
  "8_of_spades.png": 8,
  "9_of_spades.png": 9,
  "10_of_spades.png": 10,
  "jack_of_spades.png": 10,
  "queen_of_spades.png": 10,
  "king_of_spades.png": 10,
  "ace_of_spades.png": 11
};
